version: "3"
services:
  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - .:/app:ro
    environment:
      - MODE=production
    command: npm run start-dev
   